// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/tranduckhuy/go-ecommerce-backend-api/internal/controllers"
	"github.com/tranduckhuy/go-ecommerce-backend-api/internal/repositories"
	"github.com/tranduckhuy/go-ecommerce-backend-api/internal/routers/v1/product"
	"github.com/tranduckhuy/go-ecommerce-backend-api/internal/services"
)

// Injectors from wire.go:

func InitProductRouter() (*product.Router, error) {
	productRepository := repositories.NewProductRepository()
	productService := services.NewProductService(productRepository)
	productController := controllers.NewProductController(productService)
	router := product.NewRouter(productController)
	return router, nil
}

// wire.go:

var ProductSet = wire.NewSet(repositories.NewProductRepository, services.NewProductService, controllers.NewProductController, product.NewRouter)
