server:
  port: 8082
  mode: "dev"
mysql:
  host: localhost
  port: 3306
  username: root
  password: huytd
  dbname: goshop
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
logger:
  log_level: debug
  output_path: "./storages/logs/dev.001.log"
  max_backups: 3
  max_age: 28
  max_size: 10
  compress: true
  encoding: "json"
redis:
  host: localhost
  port: 6379
  password:
  database: 0
  pool_size: 10
jwt:
  TOKEN_HOUR_LIFESPAN: 1
  JWT_EXPIRATION: 1h
  API_SECRET: "xxx.yyy.zzz"
